

# defini le lien avec les typologies de la table "equipement_pilote_typologie_installation_domotique"
TYPOLOGIE_2RELAIS = 110
TYPOLOGIE_PRISE = 120
TYPOLOGIE_PRISE_ET_DOIGT = 130
TYPOLOGIE_RELAI_ET_CAPTEUR = 140
TYPOLOGIE_PRISE_ET_DEUX_DOIGT = 150
TYPOLOGIE_PRISE_DOIGT_DOUBLE = 160
TYPOLOGIE_PRISE_RALLUME_DOIGT = 170
TYPOLOGIE_RELAI_COMPTEUR = 180

# defini le lien avec les usages de la table "equipement_domotique_usage"
USAGE_MESURE_ELEC_COMMUTER = 11
USAGE_COMMUTER = 12
USAGE_MESURE_ELEC = 21
USAGE_APPUYER_POWER = 31
USAGE_APPUYER_DEMARRAGE = 32
USAGE_MESURER_AMBIANCE = 61
USAGE_IHM = 71


DEVICE_ACTION_ON = "ON"
DEVICE_ACTION_OFF = "OFF"

EQUIPEMENT_PILOTE_MODE_MANUEL = '20'
EQUIPEMENT_PILOTE_MODE_PILOTE = '30'
EQUIPEMENT_PILOTE_MODE_PILOTE_NUM = 30

EQUIPEMENT_PILOTE_TYPE_SCREEN = 711

SCREEN_OBJ_LED = 10
SCREEN_OBJ_TIME_HOUR = 8
SCREEN_OBJ_TIME_MINUTE = 9

SCREEN_OBJ_VOITURE_TIME_HOUR = 5
SCREEN_OBJ_VOITURE_TIME_MINUTE = 6
SCREEN_OBJ_VOITURE_LOAD = 8
SCREEN_OBJ_PILOTE_SWITCH = 3